Major upgrade to version v2.0

diff --git a/addon/goprobe.init b/addon/goprobe.init
--- a/addon/goprobe.init
+++ b/addon/goprobe.init
@@ -5,7 +5,7 @@
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Starts and stops the goProbe daemon 
+# Short-Description: Starts and stops the goProbe daemon
 ### END INIT INFO
 
 # This code has been developed by Open Systems AG
@@ -30,10 +30,18 @@ PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="goprobe init script"
 NAME=goprobe
 PIDFILE=/var/run/$NAME.pid
-DAEMON=/usr/local/goProbe/bin/goProbe
-# write down all interfaces on which goProbe should perform capturing
-DAEMON_ARGS="eth0"
+
+# installation directory (set during build process)
+PREFIX=
+
+DAEMON=$PREFIX/goProbe/bin/goProbe
+DAEMON_CONF=$PREFIX/goProbe/etc/goprobe.conf
+
+DAEMON_ARGS="-config $DAEMON_CONF"
 SCRIPTNAME=/etc/init.d/goprobe.init
+
+# DB Path is set by the config (the default path may not exist)
+DB_PATH=$PREFIX/goProbe/db
 
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
@@ -42,7 +50,33 @@ SCRIPTNAME=/etc/init.d/goprobe.init
 . /lib/lsb/init-functions
 
 # change this if you installed goProbe in a custom location
-export LD_LIBRARY_PATH=/usr/local/goProbe/lib
+export LD_LIBRARY_PATH=$PREFIX/goProbe/lib
+
+is_configured() {
+    if [ ! -e "$DAEMON_CONF" ]; then
+        return 1
+    else
+        return 0
+    fi
+}
+
+gp_fetch_stats() {
+    local retval=0
+
+    # try to extract DB_PATH
+    if is_configured; then
+        DB_PATH=$( sed -nr "s/.*\s+?\"db_path\"\s+?:\s+?\"([^\"]*)\"\s+?,.*/\1/p" $DAEMON_CONF  )
+    else
+        return 1
+    fi
+
+    states=$( echo "STATUS" | socat - UNIX-CONNECT:$DB_PATH/control.sock | sed 's/^DONE$//' )
+    if [ "$states" = "" ]; then
+       retval=1
+    fi
+    echo "$states"
+    return $retval
+}
 
 do_start()
 {
@@ -86,6 +120,10 @@ do_reload() {
 case "$1" in
   start)
     [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    if ! is_configured; then
+        echo -e "\e[00;31mFAIL\e[00m (not configured)"
+        log_end_msg 1; exit 1
+    fi
     do_start
     case "$?" in
         0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ; exit 0;;
@@ -106,6 +144,13 @@ case "$1" in
     pid=`pgrep -f "$DAEMON $DAEMON_ARGS"`
         if [ "$pid" != "" ]; then
           echo -e "\e[00;32mOK\e[00m   (PID $pid)"
+
+          # fetch interface statistics
+          if ! out=$( gp_fetch_stats ); then
+            exit 1
+          fi
+
+           echo "1 $out" | $PREFIX/goProbe/shared/gp_status.pl
     else
           echo -e "\e[00;31mFAIL\e[00m (not running)"
       retval=1
@@ -123,7 +168,7 @@ case "$1" in
               echo -e "\e[00;31mFAIL\e[00m $err"
               exit $retval
           fi
-          
+
           echo -e "\e[00;32mOK\e[00m"
     else
           echo -e "\e[00;31mFAIL\e[00m (not running)"
@@ -136,6 +181,9 @@ case "$1" in
     do_stop
     case "$?" in
       0|1)
+        if ! is_configured; then
+            log_end_msg 0; exit 0
+        fi
         do_start
         case "$?" in
             0) log_end_msg 0 ; exit 0;;
@@ -154,4 +202,4 @@ case "$1" in
     echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
     exit 3
     ;;
-esac 
+esac
